# -*- coding: utf-8 -*-
"""bmi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-t2p5t7PsZF9DzhEkrprxN4PafgEKcmA
"""

import streamlit as st

st.title("BMI Calculator")

unit_system = st.radio(
    "Choose unit system:",
    ["Metric (kg, meters)", "Imperial (lbs, feet/inches)"]
)

if unit_system == "Metric (kg, meters)":
    height_m = st.number_input("Enter height in meters:", min_value=0.0, format="%.2f")
    weight_kg = st.number_input("Enter weight in kilograms:", min_value=0.0, format="%.2f")

    if st.button("Calculate BMI"):
        if height_m > 0:
            bmi = weight_kg / (height_m ** 2)
            st.success(f"Your BMI is: {bmi:.2f}")
        else:
            st.error("Height must be greater than 0.")

else:
    feet = st.number_input("Enter height (feet):", min_value=0, step=1)
    inches = st.number_input("Enter additional inches:", min_value=0, step=1)
    weight_lbs = st.number_input("Enter weight in pounds:", min_value=0.0, format="%.2f")

    if st.button("Calculate BMI"):
        total_inches = feet * 12 + inches
        height_m = total_inches * 0.0254
        weight_kg = weight_lbs * 0.45359237

        if height_m > 0:
            bmi = weight_kg / (height_m ** 2)
            st.success(f"Your BMI is: {bmi:.2f}")
        else:
            st.error("Height must be greater than 0.")